### ISSUE TITLE
Any plans to revive this?

### ISSUE THREAD

**Issue by NeckBeardPrince** [OpenVPN/terraform-provider-openvpn-cloud-beta#1]

**Comment by dsommers** [comment]
Sorry for the long response time.  You actually happened to ask for this almost in the middle of preparing the grounds for a more proper open source project around the terraform provider.  This effort can be found here: https://github.com/OpenVPN/terraform-provider-openvpn-cloud

@arslanbekov will start with having a few more people in the beginning helping to drive this effort forward, and we hope that this project can grow with more contributors - from everywhere.  There has not yet been taken any decision what will happen with this "-beta" repository; that is more up to this new community group to decide.

I'm closing this "issue", as I consider it solved through this new efforts.
